kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: pim-integration-server-container
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'pim-integration-server:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Binary
    binary: {}
  runPolicy: Serial
